/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ianfennen.java.guiBeans;

import com.ianfennen.java.dataObjects.BookReg;
import java.util.ArrayList;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ian Fennen
 */
public class DataTableBean extends javax.swing.JPanel {

    private ArrayList<BookReg> bookList;

    /**
     * Creates new form DataTableBean
     */
    public DataTableBean() {
        initComponents();
        bookTable.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                switch (e.getType()) {
                    case TableModelEvent.DELETE:
                        break;
                    case TableModelEvent.INSERT:
                        break;
                    case TableModelEvent.UPDATE:
                        updateBookList(null);
                        break;
                }
            }

        });
        bookList = new ArrayList();
    }

    private void updateBookList(ArrayList<BookReg> list) {
        if (list != null) {
            bookList = list;
        } else {
            DefaultTableModel dtm = (DefaultTableModel) bookTable.getModel();

            for (int i = 0; i < dtm.getRowCount(); i++) {

                String author = (String) dtm.getValueAt(i, 0);
                String title = (String) dtm.getValueAt(i, 1);
                String ISBN = (String) dtm.getValueAt(i, 2);
                System.out.println("Trying to add book");
                if (author.length() != 0 && title.length() != 0 && validateISBN(ISBN)) {
                    BookReg b = new BookReg(author, title, ISBN);
                    if (!bookList.contains(b)) {
                        bookList.add(b);
                        String blankRow[] = {"", "", ""};
                        dtm.addRow(blankRow);
                    }

                }
            }

        }
    }

    public ArrayList<BookReg> getBookList() {
        return bookList;
    }

    private boolean validateISBN(String ISBN) {
        return ISBN != null && ISBN.length() == 10 && ISBN.matches("\\d+");
    }

    public void updateTable(ArrayList<BookReg> bookList) {

        DefaultTableModel dtm = (DefaultTableModel) bookTable.getModel();
        for (BookReg b : bookList) {
            dtm.addRow(b.toArray());
        }
        Object blankRow[] = {"", "", ""};
        dtm.addRow(blankRow);

        updateBookList(bookList);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
