/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ianfennen.java.guiBeans;

import com.ianfennen.java.dataObjects.Book;
import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;

/**
 *
 * @author Ian Fennen
 */
public class GenericLoaderBean extends javax.swing.JPanel {

    private int currentCard;
    /**
     * Creates new form GenericLoaderBean
     */
    public GenericLoaderBean() {
        initComponents();
        textFileLoaderBean1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                fireNew(evt);
            }
        });
        currentCard = 0;
    }
    
    private void fireNew(PropertyChangeEvent evt){
        firePropertyChange(evt.getPropertyName(), evt.getOldValue(), evt.getNewValue());
    }
    
    public ArrayList<Book> getBookList(){
        switch(currentCard){
            case 1:
                return xMLFileLoaderBean1.getBookList();
            case 2:
                return sQLDataLoaderBean1.getBookList();
            case 0:
            default:
                return textFileLoaderBean1.getBookList();

        }
    }
    
    public void changeCard(String cardName){
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFileLoaderBean1 = new com.ianfennen.java.guiBeans.TextFileLoaderBean();
        xMLFileLoaderBean1 = new com.ianfennen.java.guiBeans.XMLFileLoaderBean();
        sQLDataLoaderBean1 = new com.ianfennen.java.guiBeans.SQLDataLoaderBean();

        setLayout(new java.awt.CardLayout());
        add(textFileLoaderBean1, "TextFileCard");
        add(xMLFileLoaderBean1, "XMLFileCard");
        add(sQLDataLoaderBean1, "SQLDataCard");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ianfennen.java.guiBeans.SQLDataLoaderBean sQLDataLoaderBean1;
    private com.ianfennen.java.guiBeans.TextFileLoaderBean textFileLoaderBean1;
    private com.ianfennen.java.guiBeans.XMLFileLoaderBean xMLFileLoaderBean1;
    // End of variables declaration//GEN-END:variables
}
