/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ianfennen.java.guiBeans;

import com.ianfennen.java.dataObjects.Book;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;

/**
 *
 * @author Ian Fennen
 */
public class MainDisplayBean extends javax.swing.JPanel {

    private ArrayList<Book> bookList;
    private int inputType;

    /**
     * Creates new form MainDisplayBean
     */
    @SuppressWarnings("Convert2Lambda")
    public MainDisplayBean() {
        initComponents();
        bookList = new ArrayList();
        genericLoaderBean1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(TextFileLoaderBean.FILE_LOADER_EVENT)) {
                    if (evt.getNewValue().equals(TextFileLoaderBean.FILE_STATE_CHANGED)) {
                        bookList = genericLoaderBean1.getBookList();
                        insertDataIntoTable(bookList);
                    }
                }
            }

        });
        updateFileBean1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(UpdateFileBean.UPDATE_FILE_EVENT)) {
                    if (evt.getNewValue().equals(UpdateFileBean.SAVE_FILE_EVENT)) {
                        updateFileBean1.saveTable(dataTableBean1.getBookList());
                    }
                }
            }
        });

        inputType = 0;
    }

    private void insertDataIntoTable(ArrayList<Book> bookList) {
        dataTableBean1.updateTable(bookList);
    }

    public void setInputMethod(int type) {
        if (inputType != type) {
            inputType = type;
            changeInputDisplay();
        }

    }

    private void changeInputDisplay() {
        switch (inputType) {
            case 1:
                genericLoaderBean1.changeCard("XMLFileCard");
                break;
            case 2:
                genericLoaderBean1.changeCard("SQLDataCard");
                break;
            case 0:
            default:
                genericLoaderBean1.changeCard("TextFileCard");
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTableBean1 = new com.ianfennen.java.guiBeans.DataTableBean();
        updateFileBean1 = new com.ianfennen.java.guiBeans.UpdateFileBean();
        genericLoaderBean1 = new com.ianfennen.java.guiBeans.GenericLoaderBean();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataTableBean1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateFileBean1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genericLoaderBean1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genericLoaderBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(dataTableBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateFileBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ianfennen.java.guiBeans.DataTableBean dataTableBean1;
    private com.ianfennen.java.guiBeans.GenericLoaderBean genericLoaderBean1;
    private com.ianfennen.java.guiBeans.UpdateFileBean updateFileBean1;
    // End of variables declaration//GEN-END:variables
}
