/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ianfennen.java.guiBeans;

import com.ianfennen.java.dataObjects.BookReg;
import com.ianfennen.java.guiBeans.interfaces.FileInputMethod;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian Fennen
 */
public class TextFileLoaderBean extends FileInputMethod {

    public static final String FILE_LOADER_EVENT = "FILE_LOADER_EVENT";
    public static final String FILE_STATE_CHANGED = "FILE_STATE_CHANGED";

    /**
     * Creates new form FileLoaderBean
     */
    public TextFileLoaderBean() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileNameLbl = new javax.swing.JLabel();
        inputFileField = new javax.swing.JTextField();
        browseFileBtn = new javax.swing.JButton();
        loadFileBtn = new javax.swing.JButton();

        inputFileNameLbl.setText("Input File Name: ");

        inputFileField.setText("C:\\Users\\Ian Fennen\\Desktop\\books2.csv");

        browseFileBtn.setText("Browse File");
        browseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFileBtnActionPerformed(evt);
            }
        });

        loadFileBtn.setText("Load File");
        loadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputFileNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseFileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadFileBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileNameLbl)
                    .addComponent(inputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFileBtn)
                    .addComponent(loadFileBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFileBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        if (fileChooser.getSelectedFile() != null) {
            String fileName = fileChooser.getSelectedFile().getAbsolutePath();
            inputFileField.setText(fileName);
        }
    }//GEN-LAST:event_browseFileBtnActionPerformed

    private void loadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileBtnActionPerformed
        loadFile(inputFileField.getText());
    }//GEN-LAST:event_loadFileBtnActionPerformed

    private void loadFile(String fileName) {
        try {
            Scanner fileIn = new Scanner(new File(fileName));
            bookList = new ArrayList();
            while (fileIn.hasNext()) {
                String line = fileIn.nextLine();
                bookList.add(lineToBook(line));
            }

            firePropertyChange(FILE_LOADER_EVENT, "", FILE_STATE_CHANGED);

        } catch (FileNotFoundException | InputMismatchException e) {
            displayError("Error reading from file: " + fileName);
            bookList = null;
        }

    }

    /**
     * Converts a line of text separated by commas into a book object.
     *
     * @param line The line of text that contains the info for a {@code BookReg}
     * @return The {@code BookReg} created from {@code line}
     */
    private BookReg lineToBook(String line) throws InputMismatchException {
        try {
            String[] ar = line.split(",");
            String title = ar[0];
            String author = ar[1];
            String isbn = ar[2];
            return new BookReg(title, author, isbn);
        } catch (Exception e) {
            throw new InputMismatchException("Input File Format Invalid");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFileBtn;
    private javax.swing.JTextField inputFileField;
    private javax.swing.JLabel inputFileNameLbl;
    private javax.swing.JButton loadFileBtn;
    // End of variables declaration//GEN-END:variables
}
