/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ianfennen.java.guiBeans;

import com.ianfennen.java.dataObjects.Book;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author Ian Fennen
 */
public class UpdateFileBean extends javax.swing.JPanel {

    
    public static final String UPDATE_FILE_EVENT = "UPDATE_FILE_BEAN";
    public static final String SAVE_FILE_EVENT = "SAVE_FILE_EVENT";
    
    /**
     * Creates new form UpdateFileBean
     */
    public UpdateFileBean() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileNameLbl = new javax.swing.JLabel();
        outputFileField = new javax.swing.JTextField();
        browseForSaveBtn = new javax.swing.JButton();
        saveFileBtn = new javax.swing.JButton();

        inputFileNameLbl.setText("Output File Name: ");

        browseForSaveBtn.setText("Browse to Save");
        browseForSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseForSaveBtnActionPerformed(evt);
            }
        });

        saveFileBtn.setText("Save File");
        saveFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputFileNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseForSaveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveFileBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileNameLbl)
                    .addComponent(outputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseForSaveBtn)
                    .addComponent(saveFileBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseForSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseForSaveBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(this);
        if(fileChooser.getSelectedFile() != null){
            outputFileField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseForSaveBtnActionPerformed

    private void saveFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileBtnActionPerformed
        System.out.println("Button pressed");
        firePropertyChange(UPDATE_FILE_EVENT, "", SAVE_FILE_EVENT);
        
    }//GEN-LAST:event_saveFileBtnActionPerformed

    public void saveTable(ArrayList<Book> bookList){
        System.out.println("Save Table" + bookList.size());
        String fileName = outputFileField.getText();
        try(PrintWriter pw = new PrintWriter(new File(fileName))) {
            for(Book b : bookList){
                pw.write(b.toString() + "\n");
            }
        } catch(IOException e){
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseForSaveBtn;
    private javax.swing.JLabel inputFileNameLbl;
    private javax.swing.JTextField outputFileField;
    private javax.swing.JButton saveFileBtn;
    // End of variables declaration//GEN-END:variables
}
